# Generated by Django 4.2.7 on 2023-12-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profilemanager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="t_and_c",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
