# Generated by Django 4.2.7 on 2023-12-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profilemanager", "0002_userprofile_t_and_c"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="t_and_c",
            field=models.BooleanField(null=True),
        ),
    ]
