# Generated by Django 4.2.7 on 2023-12-13 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("artists", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artists",
            name="bookings_total",
        ),
        migrations.RemoveField(
            model_name="artists",
            name="rating",
        ),
    ]
