# Generated by Django 3.2.23 on 2023-11-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_on'], 'verbose_name': 'News'},
        ),
    ]
