# Generated by Django 3.2.23 on 2023-11-20 17:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0002_alter_news_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='NewsPosts',
        ),
        migrations.AlterModelOptions(
            name='newsposts',
            options={'ordering': ['-created_on'], 'verbose_name': 'News Posts'},
        ),
    ]
