# Generated by Django 3.2.23 on 2023-11-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20231120_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsposts',
            options={'ordering': ['-created_on'], 'verbose_name': 'News Post'},
        ),
        migrations.AddField(
            model_name='newsposts',
            name='post_body',
            field=models.TextField(default='text'),
        ),
    ]
