# Generated by Django 3.2.23 on 2023-11-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20231120_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artists',
            options={'verbose_name': 'Artist'},
        ),
        migrations.AlterModelOptions(
            name='bookings',
            options={'verbose_name': 'Booking'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created_on'], 'verbose_name': 'Comment'},
        ),
        migrations.AlterModelOptions(
            name='stylesavailable',
            options={'verbose_name': 'Available Style'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile'},
        ),
    ]
