# Generated by Django 3.2.23 on 2023-11-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_userprofile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='start_date',
            field=models.DateField(),
        ),
    ]
