# Generated by Django 3.2.23 on 2023-11-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_artists_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylesavailable',
            name='slug',
            field=models.TextField(default='hello'),
        ),
    ]
