# Generated by Django 3.2.23 on 2023-11-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_stylesavailable_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylesavailable',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
