# Generated by Django 3.2.23 on 2023-11-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_alter_stylesavailable_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscomments',
            old_name='full_name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='stylescomments',
            old_name='full_name',
            new_name='username',
        ),
    ]
