# Generated by Django 4.2.7 on 2023-11-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='marketing',
            field=models.BooleanField(),
        ),
    ]
