# Generated by Django 4.2.7 on 2023-12-10 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0018_rename_date_bookings_date_time_remove_bookings_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="username",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
