# Generated by Django 4.2.7 on 2023-12-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0020_remove_bookings_booking_confirmed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="date_time",
            field=models.DateTimeField(null=True),
        ),
    ]
