# Generated by Django 4.2.7 on 2023-12-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0021_alter_bookings_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
