# Generated by Django 4.2.7 on 2023-12-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0022_bookings_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="is_rated",
            field=models.BooleanField(default=False),
        ),
    ]
