# Generated by Django 4.2.7 on 2023-12-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylescomments',
            name='username',
        ),
    ]
