# Generated by Django 4.2.7 on 2023-12-18 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('styles', '0002_remove_stylescomments_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylescomments',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='styles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
